// AUTO-GENERATED by tools/generate_constants.py. Do not edit.
#pragma once
#include <cstdint>

namespace ir_spoke::generated {
inline constexpr std::uint32_t kConfigSchemaVersion = 2;
inline constexpr std::uint32_t kCarrierHz = 38000;
inline constexpr float kCarrierDuty = 0.5f;
inline constexpr std::uint32_t kRmtResolutionHz = 1000000;
inline constexpr std::uint32_t kRxDemodFrequencyHz = 25000;
inline constexpr std::uint32_t kGlitchFilterUs = 4;
inline constexpr std::uint32_t kMinimumBlockedUs = 70;
inline constexpr std::uint32_t kMaximumBlockedUs = 600;
inline constexpr std::uint32_t kLinkLossTimeoutUs = 15000;
inline constexpr std::uint8_t kSpokeCountMin = 16;
inline constexpr std::uint8_t kSpokeCountMax = 48;
inline constexpr std::uint16_t kSpokeCountConfidenceEvents = 192;
inline constexpr std::uint16_t kLutBins = 64;
inline constexpr float kLearningRate = 0.08f;
inline constexpr float kOutlierSigma = 3.5f;
inline constexpr float kEffectiveWheelDiameterM = 0.702f;
inline constexpr float kBeamRadiusM = 0.25f;
inline constexpr float kNominalSpokeWidthMm = 2f;
inline constexpr float kMaxSpokeEventHz = 362.746309f;
inline constexpr float kTiaPoleHz = 40190.6422f;
inline constexpr float kBandpassHighpassHz = 9947.18394f;
inline constexpr float kBandpassLowpassHz = 58946.2752f;
inline constexpr float kCalculatedLedCurrentMa = 45.3846154f;
}  // namespace ir_spoke::generated
