#!/usr/bin/env python3
"""Generate firmware and SPICE constants from the reviewed system manifest."""

from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CFG_PATH = ROOT / "config" / "system.json"
CFG = json.loads(CFG_PATH.read_text(encoding="utf-8"))


def f(value: float) -> str:
    return f"{value:.9g}"


def main() -> None:
    wheel = CFG["wheel"]
    optical = CFG["optical"]
    afe = CFG["analog_frontend"]
    tx = CFG["transmitter"]
    esp = CFG["esp32"]

    circumference = math.pi * wheel["effective_diameter_m"]
    max_wheel_hz = (wheel["max_speed_kmh"] / 3.6) / circumference
    max_spoke_hz = max_wheel_hz * wheel["spoke_count_max"]
    tia_pole_hz = 1 / (
        2 * math.pi * afe["tia_feedback_ohm"] * afe["tia_feedback_pf"] * 1e-12
    )
    hp_hz = 1 / (
        2 * math.pi * afe["ac_bias_ohm"] * afe["ac_coupling_nf"] * 1e-9
    )
    gain_lp_hz = 1 / (
        2 * math.pi * afe["gain_feedback_ohm"] * afe["gain_feedback_pf"] * 1e-12
    )
    led_ma = (
        tx["supply_v"] - tx["led_vf_v_typ"] - tx["driver_vce_sat_v_typ"]
    ) / tx["led_series_ohm"] * 1000

    header = f"""// AUTO-GENERATED by tools/generate_constants.py. Do not edit.
#pragma once
#include <cstdint>

namespace ir_spoke::generated {{
inline constexpr std::uint32_t kConfigSchemaVersion = {CFG["schema_version"]};
inline constexpr std::uint32_t kCarrierHz = {optical["carrier_hz"]};
inline constexpr float kCarrierDuty = {f(optical["carrier_duty"])}f;
inline constexpr std::uint32_t kRmtResolutionHz = {esp["rmt_resolution_hz"]};
inline constexpr std::uint32_t kRxDemodFrequencyHz = {esp["rx_demod_frequency_hz"]};
inline constexpr std::uint32_t kGlitchFilterUs = {esp["rx_glitch_filter_us"]};
inline constexpr std::uint32_t kMinimumBlockedUs = {esp["minimum_blocked_us"]};
inline constexpr std::uint32_t kMaximumBlockedUs = {esp["maximum_blocked_us"]};
inline constexpr std::uint32_t kLinkLossTimeoutUs = {esp["link_loss_timeout_us"]};
inline constexpr std::uint8_t kSpokeCountMin = {wheel["spoke_count_min"]};
inline constexpr std::uint8_t kSpokeCountMax = {wheel["spoke_count_max"]};
inline constexpr std::uint16_t kSpokeCountConfidenceEvents = {esp["spoke_count_confidence_events"]};
inline constexpr std::uint16_t kLutBins = {esp["lut_bins"]};
inline constexpr float kLearningRate = {f(esp["learning_rate"])}f;
inline constexpr float kOutlierSigma = {f(esp["outlier_sigma"])}f;
inline constexpr float kEffectiveWheelDiameterM = {f(wheel["effective_diameter_m"])}f;
inline constexpr float kBeamRadiusM = {f(wheel["beam_radius_m"])}f;
inline constexpr float kNominalSpokeWidthMm = {f(wheel["spoke_width_mm"])}f;
inline constexpr float kMaxSpokeEventHz = {f(max_spoke_hz)}f;
inline constexpr float kTiaPoleHz = {f(tia_pole_hz)}f;
inline constexpr float kBandpassHighpassHz = {f(hp_hz)}f;
inline constexpr float kBandpassLowpassHz = {f(gain_lp_hz)}f;
inline constexpr float kCalculatedLedCurrentMa = {f(led_ma)}f;
}}  // namespace ir_spoke::generated
"""
    out_header = ROOT / "firmware" / "include" / "ir_spoke_generated.h"
    out_header.parent.mkdir(parents=True, exist_ok=True)
    out_header.write_text(header, encoding="utf-8")

    spice = f"""* AUTO-GENERATED by tools/generate_constants.py. Do not edit.
.param VSUP={f(afe["supply_v"])}
.param VREF={f(afe["vref_v"])}
.param FCARRIER={optical["carrier_hz"]}
.param DUTY={f(optical["carrier_duty"])}
.param RF_TIA={afe["tia_feedback_ohm"]}
.param CF_TIA={afe["tia_feedback_pf"]}p
.param C_AC={f(afe["ac_coupling_nf"])}n
.param R_AC={afe["ac_bias_ohm"]}
.param RG_GAIN={afe["gain_ground_ohm"]}
.param RF_GAIN={afe["gain_feedback_ohm"]}
.param CF_GAIN={afe["gain_feedback_pf"]}p
.param R_COMP_IN={afe["comparator_input_ohm"]}
.param R_HYST={afe["comparator_feedback_ohm"]}
.param TPD_COMP={afe["comparator_delay_ns_typ"]}n
.param SPOKE_MIN_US={esp["minimum_blocked_us"]}
.param SPOKE_MAX_US={esp["maximum_blocked_us"]}
"""
    out_spice = ROOT / "simulation" / "generated_params.inc"
    out_spice.write_text(spice, encoding="utf-8")

    summary = {
        "config": str(CFG_PATH.relative_to(ROOT)),
        "generated_header": str(out_header.relative_to(ROOT)),
        "generated_spice": str(out_spice.relative_to(ROOT)),
        "tia_pole_hz": tia_pole_hz,
        "bandpass_highpass_hz": hp_hz,
        "bandpass_lowpass_hz": gain_lp_hz,
        "calculated_led_current_ma": led_ma,
        "max_spoke_event_hz": max_spoke_hz,
    }
    (ROOT / "config" / "derived.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
