#!/usr/bin/env python3
"""Generate SPICE electrical connectivity from the canonical hardware manifest."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from validate_kicad_netlist import validate as validate_kicad_netlist

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "hardware" / "connectivity.json"
OUTPUT_PATH = ROOT / "simulation" / "generated_connectivity.inc"


def canonical_manifest() -> tuple[dict, str]:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    encoded = json.dumps(
        manifest, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return manifest, hashlib.sha256(encoded).hexdigest()


def validate_manifest(manifest: dict) -> None:
    boards = manifest["boards"]
    all_nets: set[str] = set()
    endpoints: set[tuple[str, str, str]] = set()
    for board_name, board in boards.items():
        for ref, pins in board["components"].items():
            if not pins:
                raise ValueError(f"{board_name}:{ref} has no pins")
            for pin, net in pins.items():
                endpoint = (board_name, ref, str(pin))
                if endpoint in endpoints:
                    raise ValueError(f"duplicate endpoint {endpoint}")
                endpoints.add(endpoint)
                all_nets.add(net)

    for link in manifest["harness_links"]:
        linked_nets = []
        for side in ("from", "to"):
            item = link[side]
            endpoint = (item["board"], item["ref"], str(item["pin"]))
            if endpoint not in endpoints:
                raise ValueError(f"{link['name']} references missing {endpoint}")
            linked_nets.append(
                boards[item["board"]]["components"][item["ref"]][str(item["pin"])]
            )
        if linked_nets[0] == linked_nets[1]:
            raise ValueError(
                f"{link['name']} must join distinct board nets so cable "
                "resistance cannot be bypassed"
            )
        if float(link["series_ohm"]) <= 0:
            raise ValueError(f"{link['name']} resistance must be positive")

    missing = set(manifest["simulation"]["required_signal_nets"]) - all_nets
    if missing:
        raise ValueError(f"simulation nets absent from boards: {sorted(missing)}")
    probes = set(manifest["simulation"]["probe_nets"])
    tp_nets = {
        next(iter(pins.values()))
        for ref, pins in boards["main"]["components"].items()
        if ref.startswith("TP")
    }
    if not probes <= tp_nets:
        raise ValueError(f"missing physical probes for {sorted(probes - tp_nets)}")


def generate() -> tuple[str, str]:
    endpoint_digest = validate_kicad_netlist()
    manifest, digest = canonical_manifest()
    validate_manifest(manifest)
    main = manifest["boards"]["main"]["components"]
    remote = manifest["boards"]["remote"]["components"]

    def n(board: dict, ref: str, pin: int) -> str:
        return board[ref][str(pin)]

    links = {
        link["name"]: link for link in manifest["harness_links"]
    }
    lines = [
        "* AUTO-GENERATED by tools/generate_connectivity.py. Do not edit.",
        f"* CONNECTIVITY_SHA256={digest}",
        f"* KICAD_ENDPOINT_SHA256={endpoint_digest}",
        "* Supply and RMT-controlled low-side emitter driver.",
        f"V3V3 {n(main, 'J2', 5)} {n(main, 'J2', 6)} {{VSUP}}",
        f"VTX {n(main, 'J1', 1)} {n(main, 'J2', 6)} "
        "PULSE(0 {VSUP} {SUPPLY_RISE} 2n 2n "
        "{DUTY/FCARRIER} {1/FCARRIER})",
        f"BESP {n(main, 'J2', 5)} {n(main, 'J2', 6)} "
        "I=ternary_fcn(abs(time-{TRAN_STOP}/2)<{TRAN_STOP}*{WIFI_TX_DUTY}/2,"
        "{IESP_WIFI},{IESP_COMPUTE})",
        f"BCAN {n(main, 'J2', 5)} {n(main, 'J2', 6)} "
        "I={CAN_ENABLE}*({ICAN_IDLE}+ternary_fcn("
        "abs(time-{TRAN_STOP}/2)<{TRAN_STOP}*{CAN_BUS_DUTY}/2,"
        "{ICAN_DOMINANT_EXTRA},0))",
        f"IAFE {n(main, 'U1', 8)} {n(main, 'U1', 4)} {{IAFE_QUIESCENT}}",
        f"RBASE {n(main, 'R2', 1)} {n(main, 'R2', 2)} 1k",
        f"QTX {n(main, 'Q1', 2)} {n(main, 'Q1', 1)} "
        f"{n(main, 'Q1', 3)} S8050",
    ]
    for name in ("HARNESS_K", "HARNESS_3V3"):
        link = links[name]
        a = link["from"]
        b = link["to"]
        a_net = manifest["boards"][a["board"]]["components"][a["ref"]][str(a["pin"])]
        b_net = manifest["boards"][b["board"]]["components"][b["ref"]][str(b["pin"])]
        lines.append(f"R{name} {a_net} {b_net} {link['series_ohm']:.9g}")
    lines += [
        f"RLED {n(remote, 'R1', 1)} {n(remote, 'R1', 2)} 39",
        f"DLED {n(remote, 'D1', 2)} {n(remote, 'D1', 1)} IRLED",
        "",
        "* Reference, PIN photodiode and two TLV9062 channels.",
        f"RVR_TOP {n(main, 'R3', 1)} {n(main, 'R3', 2)} 10k",
        f"RVR_BOT {n(main, 'R4', 1)} {n(main, 'R4', 2)} 10k",
        f"CVREF {n(main, 'C1', 1)} {n(main, 'C1', 2)} 1u",
        f"BPHOTO {n(main, 'D2', 1)} {n(main, 'D2', 3)} "
        "I={IPHOTO_AMBIENT}+{IPHOTO_SIGNAL}*V(CARRIER)*V(SPOKE)",
        f"IDARK {n(main, 'D2', 1)} {n(main, 'D2', 3)} DC 1n",
        f"CPD {n(main, 'D2', 3)} {n(main, 'D2', 1)} 3.3p",
        f"XU1A {n(main, 'U1', 1)} {n(main, 'U1', 3)} "
        f"{n(main, 'U1', 2)} {n(main, 'U1', 8)} "
        f"{n(main, 'U1', 4)} TLV9062_TYP",
        f"RF_TIA {n(main, 'R5', 1)} {n(main, 'R5', 2)} {{RF_TIA}}",
        f"CF_TIA {n(main, 'C2', 1)} {n(main, 'C2', 2)} {{CF_TIA}}",
        f"CAC {n(main, 'C3', 1)} {n(main, 'C3', 2)} {{C_AC}}",
        f"RAC {n(main, 'R6', 1)} {n(main, 'R6', 2)} {{R_AC}}",
        f"XU1B {n(main, 'U1', 7)} {n(main, 'U1', 5)} "
        f"{n(main, 'U1', 6)} {n(main, 'U1', 8)} "
        f"{n(main, 'U1', 4)} TLV9062_TYP",
        f"RG {n(main, 'R7', 1)} {n(main, 'R7', 2)} {{RG_GAIN}}",
        f"RF {n(main, 'R8', 1)} {n(main, 'R8', 2)} {{RF_GAIN}}",
        f"CF {n(main, 'C4', 1)} {n(main, 'C4', 2)} {{CF_GAIN}}",
        "",
        "* Comparator, hysteresis, GPIO isolation and local bypassing.",
        f"RCOMP_IN {n(main, 'R9', 1)} {n(main, 'R9', 2)} {{R_COMP_IN}}",
        f"RHYST {n(main, 'R10', 1)} {n(main, 'R10', 2)} {{R_HYST}}",
        f"BCOMP COMP_IDEAL {n(main, 'U2', 2)} "
        f"V={{VSUP}}/2*(1+tanh(350*(V({n(main, 'U2', 3)})-V({n(main, 'U2', 4)}))))",
        f"RDELAY COMP_IDEAL {n(main, 'U2', 1)} 1k",
        f"CDELAY {n(main, 'U2', 1)} {n(main, 'U2', 2)} {{TPD_COMP/1000}}",
        f"RGPIO {n(main, 'R11', 1)} {n(main, 'R11', 2)} 100",
        f"CDEC_U1 {n(main, 'C5', 1)} {n(main, 'C5', 2)} 100n",
        f"CDEC_U2 {n(main, 'C6', 1)} {n(main, 'C6', 2)} 100n",
        "",
    ]
    text = "\n".join(lines)
    OUTPUT_PATH.write_text(text, encoding="utf-8")
    return digest, text


def main() -> None:
    digest, _ = generate()
    print(json.dumps({
        "manifest": str(MANIFEST_PATH.relative_to(ROOT)),
        "generated": str(OUTPUT_PATH.relative_to(ROOT)),
        "sha256": digest,
    }, indent=2))


if __name__ == "__main__":
    main()
